project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "How to do it in R"
  description: "A Guide to Introductory Statistics Tools in R"
  site-url: "https://jcanner.github.io/how-to-do-it-in-R"
  repo-url: https://github.com/jcanner/how-to-do-it-in-R
  repo-actions: [issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Judith Canner"
    background: "#D9E3E4"

  sidebar:
#    background: "#5D737E"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/jcanner/how-to-do-it-in-R
        text: "GitHub organization"


    style: "docked"
    search: true
    collapse-level: 1
    contents:
    - href: index.qmd
      text: "Home"
    - section: "Setup R"
      contents:
      - href: overview/code-style-guide.qmd
        text: "R Code Style Guide"
      - href: 
        text: "Intalling R and RStudio"
      - href: 
        text: "Connecting to GitHub"
    - section: "Data Visualizations with `ggformula`"  
      contents: 
      - href: data-visualization/visualization-overview.qmd
        text: "Overview of `ggformula`"
      - href: data-visualization/histograms.qmd
        text: "Histograms"
      - href: data-visualization/boxplots.qmd
        text: "Boxplots"
      - href: data-visualization/scatterplots.qmd
        text: "Scatterplots"
      - href: data-visualization/barplots.qmd
        text: "Bar Plots"

    - section: "Summary Statistics with `mosaic`"  
      contents: 
      - href: 
        text: "Overview of `mosaic`"
      - href: 
        text: "Measures of Center"
      - href: 
        text: "Measures of Spread"
      - href: 
        text: "Measure of Relationship"
      - href: 
        text: "Generating Multiple Statistics (`df_stats`)"

    - section: "Inference and Conditions"  
      contents: 
      - href: 
        text: "Confidence Interval - One Mean"
      - href: 
        text: "Independent Two Sample Inference"
      - href: 
        text: "Matched Pairs Inference"
      - href: 
        text: "Analysis of Variance"
      - href: 
        text: "Simple Linear Regression"
      - href: 
        text: "Chi-Square Goodness of Fit"
      
format:
  html:
    theme: "minty"
    mainfont: "sans-serif"
    code-copy: true
    code-overflow: wrap
    toc: true
#    linkcolor: "#5D737E"
#    highlight-style: a11y-dark

editor: source

